### ISSUE TITLE
Необходимо добавить недостающие фильтры к классу CdekSDK2\Actions\Offices

### ISSUE THREAD

**Issue by astop7** [TTATPuOT/cdek-sdk2.0#1]
Необходимо добавить недостающие фильтры к классу **CdekSDK2\Actions\Offices**
```
'code' => '',
'is_ltl' => '',
'fulfillment' => '',
```

В документации есть, а в классе отсутвуют.
Если есть возможность, проверить остальные фильтры в классах.

**Comment by TTATPuOT** [comment]
Исправил в версии `1.1.0`. Спасибо за наводку!
