### ISSUE TITLE
You must define a type for CdekSDK2\\Dto\\PickupPointList::$items

### ISSUE THREAD

**Issue by fxpw** [TTATPuOT/cdek-sdk2.0#4]
зашаренная ошибка
https://flareapp.io/share/87ndlkem

php83
из стактрейса он уходит в функцию
![image](https://github.com/TTATPuOT/cdek-sdk2.0/assets/84588274/2edc71c9-e802-423b-bb7e-3d41678ff56f)
```
$body = '{"items":' . $response->getBody() . '}';
return $this->serializer->deserialize($body, $className, 'json');
```
но раньше есть проверка что класс существует, но сам jms не может найти его описание

**Comment by fxpw** [comment]
https://github.com/schmittjoh/serializer/issues/1537
нашел в чем проблема, jms переместили в dev doctrine/annotations, без пакета выбивает эту ошибку

**Comment by TTATPuOT** [comment]
Жёстко ограничил зависимость от jms/serializer и doctrine/annotations в 1.2.0. Спасибо большое за репорт!
